const sequence=document.querySelector('.sequence');const root=document.documentElement;const countdown=document.querySelector('#countdown');const reduce=matchMedia('(prefers-reduced-motion: reduce)');let ticking=false;
function frame(){const distance=sequence.offsetHeight-document.querySelector('.stage').offsetHeight;const p=reduce.matches?0:Math.max(0,Math.min(1,-sequence.getBoundingClientRect().top/Math.max(1,distance)));root.style.setProperty('--p',p);root.style.setProperty('--intro',Math.max(0,1-p*3.7));root.style.setProperty('--middle',Math.max(0,Math.min(1,(p-.2)*5,(.82-p)*6)));root.style.setProperty('--end',Math.max(0,Math.min(1,(p-.72)*5)));countdown.textContent='00:'+String(Math.max(0,Math.ceil(6-p*6))).padStart(2,'0');ticking=false;}addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(frame);ticking=true;}},{passive:true});addEventListener('resize',frame);frame();
const chapters={'2013':['USA PERPIGNAN','The first professional chapter. French rugby, a new stage, and an Italy debut in the same year.'],'2016':['BENETTON RUGBY','Five seasons in Treviso. A return to Italy, and a place in Benetton’s first Pro14 playoff campaign.'],'2021':['HARLEQUINS','A move to London. Two seasons bringing his game to the English Premiership.'],'2023':['USA PERPIGNAN','Back to the Stade Aimé Giral. A second chapter in the city where his professional career began.'],'2026':['ZEBRE PARMA','The route leads home again. A return to Italy for the 2026/27 season with Zebre Parma.']};document.querySelectorAll('.career button').forEach(b=>{b.setAttribute('aria-pressed',b.classList.contains('active'));b.addEventListener('click',()=>{document.querySelectorAll('.career button').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-pressed','false')});b.classList.add('active');b.setAttribute('aria-pressed','true');document.querySelector('#year').textContent=b.dataset.year;document.querySelector('#club').textContent=chapters[b.dataset.year][0];document.querySelector('#chapter').textContent=chapters[b.dataset.year][1];});});

// Layered rain, rendered over the original photograph without altering it.
const canvas=document.querySelector('#rain');const ctx=canvas.getContext('2d');const motionButton=document.querySelector('#motion-toggle');let rainWidth=0,rainHeight=0,drops=[],motionPaused=false,lastTime=0,rainFrame=0;const stage=document.querySelector('.stage');let stageVisible=true;
function makeDrop(randomY=true){const depth=Math.random();return{x:Math.random()*rainWidth*1.3-rainWidth*.15,y:randomY?Math.random()*rainHeight:-40,depth,speed:85+depth*280,length:2+depth*14,width:.5+depth*1.5,alpha:.12+depth*.35};}
function sizeRain(){const r=stage.getBoundingClientRect();rainWidth=r.width;rainHeight=r.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(rainWidth*dpr);canvas.height=Math.round(rainHeight*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);drops=Array.from({length:Math.min(280,Math.round(rainWidth*rainHeight/4200))},()=>makeDrop());}
function drawRain(time){rainFrame=0;if(motionPaused||reduce.matches||document.hidden||!stageVisible){lastTime=0;return;}const dt=Math.min((time-(lastTime||time))/1000,.045);lastTime=time;const p=parseFloat(getComputedStyle(root).getPropertyValue('--p'))||0;ctx.clearRect(0,0,rainWidth,rainHeight);const releaseSpeed=1+Math.max(0,p-.65)*3;for(const d of drops){d.y+=d.speed*dt*releaseSpeed;d.x-=d.speed*.26*dt; if(d.y>rainHeight+40||d.x<-70){Object.assign(d,makeDrop(false));d.x=Math.random()*(rainWidth+100);}ctx.beginPath();ctx.strokeStyle='rgba(215,235,255,'+d.alpha+')';ctx.lineWidth=d.width;ctx.lineCap='round';ctx.moveTo(d.x,d.y);ctx.lineTo(d.x-d.length*.26,d.y+d.length);ctx.stroke();if(d.depth>.94){ctx.beginPath();ctx.fillStyle='rgba(230,242,255,.12)';ctx.arc(d.x,d.y,2+d.depth*2,0,Math.PI*2);ctx.fill();}}rainFrame=requestAnimationFrame(drawRain);}
function resumeRain(){if(!rainFrame&&!motionPaused&&!reduce.matches&&!document.hidden&&stageVisible)rainFrame=requestAnimationFrame(drawRain);}
motionButton.addEventListener('click',()=>{motionPaused=!motionPaused;document.body.classList.toggle('motion-paused',motionPaused);document.querySelector('.photograph').style.animationPlayState=motionPaused?'paused':'running';motionButton.setAttribute('aria-pressed',String(!motionPaused));motionButton.setAttribute('aria-label',motionPaused?'Play rain and camera motion':'Pause rain and camera motion');motionButton.innerHTML=motionPaused?'PLAY MOTION <span>▷</span>':'PAUSE MOTION <span>Ⅱ</span>';resumeRain();});
new IntersectionObserver(entries=>{stageVisible=entries[0].isIntersecting;document.querySelector('.photograph').style.animationPlayState=stageVisible&&!motionPaused?'running':'paused';resumeRain();}).observe(stage);addEventListener('resize',()=>{sizeRain();resumeRain()});document.addEventListener('visibilitychange',resumeRain);reduce.addEventListener('change',resumeRain);sizeRain();resumeRain();

document.documentElement.classList.add('enhanced');const revealObserver=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){entry.target.classList.add('in-view');revealObserver.unobserve(entry.target)}},{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const countObserver=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){const el=entry.target,target=Number(el.dataset.count);countObserver.unobserve(el);if(reduce.matches)return;let start;function tick(t){start??=t;const p=Math.min(1,(t-start)/1600),v=Math.round(target*(1-Math.pow(1-p,3)));el.textContent=v.toLocaleString('en-US');if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}},{threshold:.7});document.querySelectorAll('[data-count]').forEach(el=>countObserver.observe(el));

document.querySelectorAll('.play-video').forEach(button=>button.addEventListener('click',()=>{const iframe=document.createElement('iframe');iframe.src='https://www.youtube.com/embed/'+button.dataset.video+'?autoplay=1';iframe.title=button.getAttribute('aria-label');iframe.allow='autoplay; encrypted-media; picture-in-picture; fullscreen';iframe.referrerPolicy='strict-origin-when-cross-origin';iframe.allowFullscreen=true;const fallback=document.createElement('a');fallback.className='video-fallback';fallback.href='https://www.youtube.com/watch?v='+button.dataset.video;fallback.target='_blank';fallback.rel='noopener';fallback.textContent='Open on YouTube ↗';button.parentElement.append(fallback);button.replaceWith(iframe);iframe.focus()}));

document.querySelectorAll('a[href="#stat-sources"]').forEach(a=>a.addEventListener('click',()=>{document.querySelector('#stat-sources').open=true}));
